style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  MaxLineLength:
    maxLineLength: 120
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
complexity:
  CyclomaticComplexMethod:
    threshold: 20
  LongMethod:
    threshold: 80
